# Data
model_id = "google/flan-t5-base"
data_file = "data/sample_nlu_data.csv"  #"data/cleaned_annotated.csv #"/content/drive/MyDrive/secret_sauce_ai/cleaned_annotated.csv"
processed_data_file = "data/processed/task_sample_data.csv"
entity_training = true
domain_intent_training = true
# Model
test_split = 0.2
model_output_directory = "models/flan_t5_base_intent_ner"
learning_rate = 2e-5
per_device_train_batch_size = 4
per_device_eval_batch_size = 4
num_train_epochs = 10
early_stopping_patience = 3
# Inference
predictions_output_file = "data/output/sample_predictions.csv"